export type NewsCategory =
  | 'Smart Cities'
  | 'Urban Mobility'
  | 'Infrastructure'
  | 'Sustainability'
  | 'Governance & Policy'
  | 'Technology in Cities';

export type SmartCityRole =
  | 'Urban Data Analyst'
  | 'Smart Mobility Analyst'
  | 'City Operations Analyst';

export interface NewsArticle {
  id: string;
  title: string;
  summary: string;
  content: string;
  category: NewsCategory;
  source: string;
  publishedDate: string;
  imageUrl?: string;
  url?: string; // Link to original article
  relatedRoles: SmartCityRole[];
  skillsMentioned: string[];
  careerRelevance: string;
  aiSummary?: string;
}

export const newsCategories: NewsCategory[] = [
  'Smart Cities',
  'Urban Mobility',
  'Infrastructure',
  'Sustainability',
  'Governance & Policy',
  'Technology in Cities',
];

export const mockNewsArticles: NewsArticle[] = [
  {
    id: '1',
    title: 'Singapore Launches AI-Powered Traffic Management System',
    summary: 'Singapore implements real-time AI analytics to optimize traffic flow, reducing commute times by 15% in pilot areas.',
    content: `Singapore has unveiled a groundbreaking AI-powered traffic management system that uses real-time data analytics to optimize traffic flow across the city-state. The system, developed in partnership with local tech companies, analyzes traffic patterns from thousands of sensors and cameras to predict congestion and adjust traffic signals dynamically.

The pilot program, which ran in three districts over six months, showed remarkable results: average commute times decreased by 15%, and carbon emissions from idling vehicles dropped by 8%. The system uses machine learning algorithms to learn from historical patterns and adapt to real-time conditions.

"This represents a significant leap forward in urban mobility," said Dr. Sarah Chen, Director of Smart City Initiatives. "By leveraging AI and IoT sensors, we're not just managing traffic—we're creating a more responsive, efficient urban environment."

The technology integrates data from multiple sources including GPS trackers in buses, traffic cameras, and mobile app data from commuters. This comprehensive approach allows the system to make decisions that benefit the entire transportation network, not just individual intersections.

For professionals in Smart Cities, this project highlights the growing importance of data analytics, IoT systems, and real-time decision-making capabilities. Urban Data Analysts play a crucial role in interpreting the vast amounts of data generated by such systems, while Smart Mobility Analysts help design and optimize these solutions.`,
    category: 'Urban Mobility',
    source: 'Smart City Journal',
    publishedDate: '2024-01-15',
    relatedRoles: ['Urban Data Analyst', 'Smart Mobility Analyst'],
    skillsMentioned: ['Data Analytics', 'IoT Systems', 'Machine Learning', 'Traffic Modeling', 'Real-time Analytics'],
    careerRelevance: 'This project demonstrates the critical role of data-driven decision making in urban mobility. Professionals working on similar initiatives need strong skills in data analysis, IoT integration, and understanding of transportation systems.',
  },
  {
    id: '2',
    title: 'Copenhagen Achieves Carbon Neutrality Through Smart Grid Technology',
    summary: 'Denmark\'s capital reaches carbon neutrality milestone using intelligent energy management and citizen engagement platforms.',
    content: `Copenhagen has officially achieved carbon neutrality, becoming one of the first major cities to reach this milestone. The achievement comes after a decade-long initiative that combined smart grid technology, renewable energy infrastructure, and innovative citizen engagement programs.

The city's smart grid system monitors energy consumption in real-time, automatically adjusting supply from renewable sources like wind and solar. When renewable energy is abundant, the system stores excess power in battery networks and electric vehicle charging stations. During peak demand, stored energy is distributed back to the grid.

What makes Copenhagen's approach unique is its integration of citizen participation. Residents can track their energy consumption through a mobile app, receive personalized recommendations for reducing their carbon footprint, and even sell excess solar energy back to the grid.

"The key to our success was making sustainability accessible and engaging for every citizen," explained Mayor Lars Jensen. "Technology alone isn't enough—you need people to understand and participate in the solution."

The smart grid infrastructure includes over 50,000 IoT sensors monitoring everything from building energy consumption to street lighting efficiency. Data analysts work continuously to optimize the system, identifying patterns and opportunities for improvement.

This achievement showcases the intersection of technology, policy, and citizen engagement—core areas where Smart City professionals can make significant impact. City Operations Analysts are essential for coordinating such large-scale initiatives, while Urban Data Analysts help interpret the complex data streams from smart infrastructure.`,
    category: 'Sustainability',
    source: 'Urban Sustainability Today',
    publishedDate: '2024-01-12',
    relatedRoles: ['City Operations Analyst', 'Urban Data Analyst'],
    skillsMentioned: ['Smart Grid Technology', 'Energy Management', 'IoT Sensors', 'Data Analysis', 'Citizen Engagement', 'Sustainability Planning'],
    careerRelevance: 'This case study highlights the growing demand for professionals who can bridge technology, policy, and community engagement. Skills in energy systems, data analytics, and stakeholder management are increasingly valuable.',
  },
  {
    id: '3',
    title: 'Barcelona Implements Digital Twin for Urban Planning',
    summary: 'Barcelona creates a comprehensive 3D digital model of the city to simulate urban development scenarios and optimize resource allocation.',
    content: `Barcelona has launched one of the world's most advanced digital twin projects, creating a comprehensive 3D virtual model of the entire city. This digital replica allows urban planners to simulate development scenarios, test infrastructure changes, and optimize resource allocation before implementing real-world changes.

The digital twin integrates data from multiple sources: building information systems, traffic sensors, environmental monitors, and citizen feedback platforms. Urban planners can now visualize how a new metro line would affect traffic patterns, or how a new park would impact local air quality—all before breaking ground.

"We're essentially building a crystal ball for urban planning," said Maria Rodriguez, Chief Technology Officer for Barcelona's Smart City Office. "We can test hundreds of scenarios in minutes, something that would take months or years in the physical world."

The system uses advanced simulation software and machine learning to predict outcomes based on historical data and current conditions. For example, when planning a new residential development, the digital twin can predict its impact on water usage, energy consumption, traffic congestion, and even social dynamics.

The project has already influenced several major decisions. When planning a new bike lane network, the digital twin revealed that a proposed route would actually increase congestion in adjacent areas. Planners adjusted the design, resulting in a 20% better outcome than the original proposal.

This technology represents the future of urban planning, where data-driven decision making becomes the norm. Urban Data Analysts are crucial for maintaining and interpreting the vast datasets that power digital twins, while City Operations Analysts coordinate the implementation of insights derived from these models.`,
    category: 'Technology in Cities',
    source: 'Future Cities Magazine',
    publishedDate: '2024-01-10',
    relatedRoles: ['Urban Data Analyst', 'City Operations Analyst'],
    skillsMentioned: ['Digital Twin Technology', '3D Modeling', 'Urban Planning', 'Simulation', 'Data Integration', 'Machine Learning'],
    careerRelevance: 'Digital twins represent a cutting-edge application of data science in urban planning. Professionals interested in this field need strong technical skills combined with understanding of urban systems and planning principles.',
  },
  {
    id: '4',
    title: 'Amsterdam Launches Citizen-Centric Data Platform',
    summary: 'New platform gives residents control over their data while enabling city services to improve through anonymized insights.',
    content: `Amsterdam has launched a revolutionary citizen data platform that puts residents in control of their personal information while enabling the city to improve services through anonymized, aggregated insights. The platform addresses growing concerns about data privacy while still allowing cities to benefit from data-driven governance.

The system works through a "data wallet" concept where citizens can choose what information to share, with whom, and for how long. For example, a resident might allow the city to use their location data (anonymized) to improve public transit routes, but opt out of sharing health information.

"This is about building trust," explained Jan van der Berg, Amsterdam's Chief Data Officer. "We're showing that cities can be smart and data-driven while respecting individual privacy and giving citizens control."

The platform has already led to several improvements. By analyzing anonymized mobility data, the city identified underserved transit routes and adjusted bus schedules accordingly, increasing ridership by 12%. Similarly, analyzing energy consumption patterns (with consent) helped identify neighborhoods that would benefit most from energy efficiency programs.

The technology uses advanced privacy-preserving techniques like differential privacy and federated learning, ensuring that individual data cannot be re-identified even when aggregated.

This initiative highlights the growing importance of data governance, privacy, and ethical AI in Smart City projects. Urban Data Analysts working on such platforms need to understand both technical data analysis and the policy implications of data use.`,
    category: 'Governance & Policy',
    source: 'Smart Governance Weekly',
    publishedDate: '2024-01-08',
    relatedRoles: ['Urban Data Analyst', 'City Operations Analyst'],
    skillsMentioned: ['Data Governance', 'Privacy Technology', 'Citizen Engagement', 'Data Analytics', 'Policy Analysis', 'Ethical AI'],
    careerRelevance: 'This project demonstrates the critical intersection of technology, policy, and ethics in Smart Cities. Professionals need to understand both technical data skills and the governance frameworks that ensure responsible data use.',
  },
  {
    id: '5',
    title: 'Tokyo Deploys AI for Disaster Preparedness',
    summary: 'Advanced AI system predicts natural disaster impacts and optimizes emergency response, reducing response time by 30%.',
    content: `Tokyo has implemented an AI-powered disaster preparedness system that can predict the impact of earthquakes, typhoons, and floods, enabling faster and more effective emergency responses. The system analyzes historical disaster data, real-time weather information, and urban infrastructure maps to model potential scenarios.

When a disaster is predicted, the AI system automatically generates evacuation routes, identifies vulnerable populations, and allocates emergency resources. During the system's first major test during a typhoon last year, response times improved by 30% compared to previous disasters.

"The system doesn't just predict what will happen—it tells us what we should do about it," said Dr. Hiroshi Tanaka, Director of Emergency Management. "It's like having a team of expert planners working 24/7."

The AI considers multiple factors: building structural integrity, population density, accessibility of emergency services, and even social factors like language barriers that might affect evacuation effectiveness. The system continuously learns from each event, improving its predictions over time.

The technology integrates with Tokyo's broader Smart City infrastructure, using data from traffic sensors, building management systems, and citizen mobile apps. During emergencies, the system can automatically adjust traffic signals to clear evacuation routes and send targeted alerts to residents in affected areas.

This application of AI in urban resilience demonstrates how technology can save lives and protect communities. City Operations Analysts play a crucial role in coordinating such systems, ensuring that technology integrates seamlessly with human emergency response teams.`,
    category: 'Infrastructure',
    source: 'Resilient Cities Report',
    publishedDate: '2024-01-05',
    relatedRoles: ['City Operations Analyst', 'Urban Data Analyst'],
    skillsMentioned: ['AI & Machine Learning', 'Disaster Management', 'Emergency Response', 'Risk Assessment', 'Data Modeling', 'Systems Integration'],
    careerRelevance: 'Urban resilience and disaster preparedness are growing priorities for cities worldwide. Professionals in this space need technical skills in AI and data analysis, combined with understanding of emergency management and infrastructure systems.',
  },
  {
    id: '6',
    title: 'Portland Launches Open Data Initiative for Transparency',
    summary: 'City releases comprehensive datasets to enable citizen analysis and improve government accountability.',
    content: `Portland has launched one of the most comprehensive open data initiatives in the United States, releasing over 200 datasets covering everything from budget allocations to environmental monitoring. The initiative aims to increase government transparency, enable citizen analysis, and foster innovation through data accessibility.

The open data portal includes interactive visualizations, API access for developers, and detailed documentation. Citizens can now analyze city spending, track environmental trends, monitor infrastructure projects, and even build their own applications using city data.

"We're democratizing data," said Mayor Lisa Chen. "When citizens have access to the same information as city officials, we can work together more effectively to solve urban challenges."

The initiative has already sparked several community-led projects. A group of local developers created an app that helps residents find the most efficient public transit routes. Another project uses environmental data to create air quality alerts for sensitive populations.

The city has also established a data governance framework that ensures privacy while maximizing data utility. Personal information is carefully anonymized, and datasets are regularly updated to maintain accuracy.

This open data movement represents a shift toward more transparent, collaborative governance. Urban Data Analysts are essential for maintaining these datasets, ensuring data quality, and helping citizens understand how to use the information effectively.`,
    category: 'Governance & Policy',
    source: 'Civic Tech Today',
    publishedDate: '2024-01-03',
    relatedRoles: ['Urban Data Analyst'],
    skillsMentioned: ['Open Data', 'Data Visualization', 'API Development', 'Data Governance', 'Civic Engagement', 'Transparency'],
    careerRelevance: 'Open data initiatives are creating new opportunities for data professionals who want to work in the public sector. Skills in data management, visualization, and civic engagement are highly valued.',
  },
  {
    id: '7',
    title: 'Stockholm Tests Autonomous Public Transit',
    summary: 'Self-driving buses begin pilot program in designated zones, potentially revolutionizing urban mobility.',
    content: `Stockholm has launched a pilot program for autonomous public transit buses, testing self-driving vehicles in designated zones throughout the city. The program, which runs for six months, aims to evaluate the feasibility, safety, and public acceptance of autonomous transit systems.

The autonomous buses use a combination of sensors, cameras, and AI to navigate predetermined routes. They're designed to integrate seamlessly with existing public transit, connecting passengers to main transit hubs. The buses operate at lower speeds (max 20 km/h) and include a human safety operator who can take control if needed.

"Autonomous transit could revolutionize how we think about public transportation," said Transport Director Erik Andersson. "It allows us to provide service in areas where traditional buses aren't economically viable, improving accessibility for all residents."

Early results show high public acceptance, with 78% of passengers rating their experience as positive. The buses have maintained a perfect safety record, with zero incidents during the first three months of operation.

The technology generates vast amounts of data about traffic patterns, passenger behavior, and system performance. Analysts are using this data to optimize routes, predict maintenance needs, and improve the overall transit experience.

This pilot represents the cutting edge of urban mobility innovation. Smart Mobility Analysts are crucial for evaluating such systems, analyzing performance data, and planning for broader implementation.`,
    category: 'Urban Mobility',
    source: 'Mobility Innovation News',
    publishedDate: '2024-01-01',
    relatedRoles: ['Smart Mobility Analyst', 'Urban Data Analyst'],
    skillsMentioned: ['Autonomous Vehicles', 'Public Transit', 'Mobility Innovation', 'Data Analysis', 'Transportation Planning', 'Safety Systems'],
    careerRelevance: 'Autonomous and connected vehicles represent the future of urban mobility. Professionals in this space need to understand both transportation systems and emerging technologies like AI and sensor networks.',
  },
];

// Get featured article (most recent)
export const getFeaturedArticle = (): NewsArticle => {
  return mockNewsArticles[0];
};

// Get articles by category
export const getArticlesByCategory = (category: NewsCategory | 'All'): NewsArticle[] => {
  if (category === 'All') {
    return mockNewsArticles;
  }
  return mockNewsArticles.filter(article => article.category === category);
};

// Get article by ID
export const getArticleById = (id: string): NewsArticle | undefined => {
  return mockNewsArticles.find(article => article.id === id);
};

// Get trending topics (categories with most articles)
export const getTrendingTopics = (): NewsCategory[] => {
  const categoryCounts = newsCategories.map(category => ({
    category,
    count: mockNewsArticles.filter(a => a.category === category).length,
  }));

  return categoryCounts
    .sort((a, b) => b.count - a.count)
    .slice(0, 4)
    .map(item => item.category);
};
